APP_NAME := ButtonsTest
ARDUINO_LIBS := AUnit ezButton ductfan-control
ARDUINO_LIB_DIRS := \
	/home/simon/Arduino/libraries \
	../../../../..
EXTRA_CXXFLAGS := '-fexceptions'
include ../../../../epoxyduino/EpoxyDuino/EpoxyDuino.mk
